void makeBox(int, int, int, int);
void showMenu();
void showLevelMenu();
void showGame(int);
void showSenario(int);
void showleftTime(int);
void showNowLocation(int);
void showText(int,char*);
void showMyText(char*);
void showDeveloper();
void showPerson(int);